[package]
edition = "2021"
name = "gfx-macros"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0.42", features = ["proc-macro"] }
proc-macro2 = { version = "1.0.103", features = ["proc-macro"] }
syn = { version = "2.0.110", features = ["derive", "parsing", "proc-macro"] }
